var wordlist = [
{en : "dog", fr : "le chien/la chienne"},
{en : "cat", fr : "le chat/la chatte"},
{en : "mouse", fr : "la souris"},
{en : "bird", fr : "oiseau"},
{en : "chicken/rooster", fr : "la poulet/le coq"},
{en : "cow", fr : "la vache"},
{en : "duck", fr : "le canard"},
{en : "goat", fr : "la chèvres"},
{en : "horse", fr : "le cheval"},
{en : "pig", fr : "le cochon"},
{en : "sheep", fr : "le mouton"},
{en : "lion", fr : "lion"},
{en : "tiger", fr : "tigre"},
{en : "bear", fr : "ours"},
{en : "elephant", fr : "éléphant"},
{en : "monkey", fr : "singe"},
{en : "skunk", fr : "mouffette"},
{en : "opossum", fr : "sarigue"},
{en : "eagle", fr : "aigle"},
{en : "fish", fr : "poissons"},
{en : "whale", fr : "baleine"},
{en : "forest", fr : "la forêt"},
{en : "trees", fr : "arbres"},
{en : "plant", fr : "la plante"},
{en : "flower", fr : "la fleur"},
{en : "jungle", fr : "la jungle"},
{en : "ocean", fr : "l'océan"},
{en : "river", fr : "le fleuve"},
{en : "pond", fr : "l'étang"},
{en : "lake", fr : "le lac"},
{en : "hill", fr : "la colline"},
{en : "mountain", fr : "la montagne"},
{en : "waterfall", fr : "la cascade"},
{en : "rainbow", fr : "arc-en-ciel"},
{en : "sky", fr : "le ciel"},
{en : "cloud", fr : "le nuage"},
{en : "rain", fr : "pluie"},
{en : "snow", fr : "neige"},
{en : "head", fr : "la tête"},
{en : "brain", fr : "le cerveau"},
{en : "hair", fr : "les cheveux"},
{en : "face", fr : "le visage"},
{en : "ear", fr : "l'oreille"},
{en : "eye", fr : "l'æil"},
{en : "mouth", fr : "la bouche"},
{en : "nose", fr : "le nez"},
{en : "neck", fr : "le cou"},
{en : "shoulder", fr : "l'épaule"},
{en : "chest", fr : "la poitrine"},
{en : "stomach", fr : "l'estomac"},
{en : "waist", fr : "la taille"},
{en : "back", fr : "le dos"},
{en : "heart", fr : "le cæur"},
{en : "arm", fr : "le bras"},
{en : "elbow", fr : "le coude"},
{en : "wrist", fr : "le poignet"},
{en : "hand", fr : "la main"},
{en : "finger", fr : "les doigts"},
{en : "leg", fr : "la jambe"},
{en : "thigh", fr : "la cuisse"},
{en : "shin", fr : "le tibia"},
{en : "foot", fr : "le pied"},
{en : "toe", fr : "les orteils"},
{en : "hat", fr : "le chapeau"},
{en : "earrings", fr : "les boucles d'oreilles"},
{en : "shirt", fr : "la chemise"},
{en : "blouse", fr : "le chemisier"},
{en : "dress", fr : "la robe"},
{en : "pants", fr : "le pantalon"},
{en : "jeans", fr : "le jean"},
{en : "shorts", fr : "le short"},
{en : "skirt", fr : "la jupe"},
{en : "socks", fr : "la chaussette"},
{en : "shoes", fr : "la chaussure"},
{en : "swimsuit", fr : "le maillot de bain"},
{en : "pajamas", fr : "le pyjama"},
{en : "underwear", fr : "les sous-vêtements"},
{en : "gloves", fr : "les gants"},
{en : "belt", fr : "la ceinture"},
{en : "coat", fr : "le manteau"},
{en : "ring", fr : "la bague"},
{en : "My arm hurts.", fr : "Mon bras fait mal."},
{en : "Are you hurt?", fr : "Êtes-vous blessé?"},
{en : "I have a headache.", fr : "J'ai mal à la tête."},
{en : "Do you have aspirin?", fr : "Avez-vous un aspirine?"},
{en : "You are hurting me.", fr : "Tu me fais mal."},
{en : "Don't hurt him/her.", fr : "Ne lui faites pas mal."},
{en : "business", fr : "affaires"},
{en : "office", fr : "le bureau"},
{en : "city", fr : "la ville"},
{en : "the rent", fr : "le loyer"},
{en : "tax", fr : "impôt"},
{en : "the cost", fr : "le coût"},
{en : "price", fr : "prix"},
{en : "bill", fr : "facture"},
{en : "estimate", fr : "évaluation"},
{en : "check", fr : "chèque"},
{en : "travelers check", fr : "chèque de voyage"},
{en : "balance", fr : "équilibre"},
{en : "passport", fr : "passeport"},
{en : "luggage/baggage", fr : "bagage"},
{en : "currency/exchange", fr : "change"},
{en : "customs", fr : "les douanes"},
{en : "entrance", fr : "entrée"},
{en : "exit", fr : "sortie"},
{en : "information", fr : "l'information"},
{en : "to pay", fr : "payer"},
{en : "to buy", fr : "acheter"},
{en : "to sell", fr : "se vendre"},
{en : "to cost", fr : "au coût"},
{en : "to rent", fr : "au loyer"},
{en : "to deposit", fr : "déposer"},
{en : "actor (m/f)", fr : "l'acteur/l'actrice"},
{en : "accountant", fr : "le comptable/la comptable"},
{en : "architect", fr : "l'architecte"},
{en : "attorney/lawyer", fr : "l'avocat/l'avocate"},
{en : "baker", fr : "le boulanger/la boulangére"},
{en : "banker", fr : "le banquier/la banquiére"},
{en : "business person", fr : "l'homme/la femme d'affaires"},
{en : "carpenter", fr : "le charpentier/la charpentier"},
{en : "computer programmer", fr : "le programmeur/la programmeuse"},
{en : "cook", fr : "le cuisinier/la cuisinierière"},
{en : "dentist", fr : "le dentiste/la dentiste"},
{en : "doctor", fr : "le médecin/la médecin"},
{en : "electrician", fr : "électricien"},
{en : "engineer", fr : "l'ingénieur/l'ingénieure"},
{en : "factory worker", fr : "l'ouvrier/l'ouvriére"},
{en : "fire fighter", fr : "le pompier/la pompier"},
{en : "hair dresser", fr : "le coiffeur/la coiffeuse"},
{en : "judge", fr : "le juge/la juge"},
{en : "librarian", fr : "le bibliothécaire/la bibliothécaire"},
{en : "mechanic", fr : "mécanicien"},
{en : "nurse", fr : "l'infirmier/l'infirmière"},
{en : "pharmacist", fr : "le pharmacien/la pharmacienne"},
{en : "police officer", fr : "l'agent de police"},
{en : "postal worker", fr : "le facteur/la factrice"},
{en : "professor", fr : "le professeur/la professeur"},
{en : "psychologist", fr : "le psychologue/la psychologue"},
{en : "reporter", fr : "le journaliste/la journaliste"},
{en : "retired", fr : "le retraité/la retraitée"},
{en : "salesperson", fr : "le vendeur/la vendeuse"},
{en : "secretary", fr : "secrétaire"},
{en : "singer", fr : "le chanteur/la chanteuse"},
{en : "student", fr : "l'étudiant/l'étudiante"},
{en : "taxi driver", fr : "le chauffeur de taxi/la chauffeur de taxi"},
{en : "teacher", fr : "l'instituteur/l'institutrice"},
{en : "veterinarian", fr : "le vétérinaire/la vétérinaire"},
{en : "writer", fr : "l'écrivain/l'écrivaine"},
{en : "driving directions", fr : "direcciones"},
{en : "How do we get to _?", fr : "Comment arrivons-nous à _?"},
{en : "Where is _?", fr : "Où est _?"},
{en : "What time does it leave?", fr : "Quel temps faut-il partir?"},
{en : "Can you draw it for me?", fr : "Pouvez-vous dessiner pour moi?"},
{en : "map", fr : "plan"},
{en : "corner", fr : "coin"},
{en : "street", fr : "rue"},
{en : "city", fr : "ville"},
{en : "downtown", fr : "centre-ville"},
{en : "to accelerate", fr : "accélérer"},
{en : "to brake", fr : "freiner"},
{en : "to stop", fr : "s'arrêter"},
{en : "to go", fr : "pour aller"},
{en : "turn left", fr : "tourner à gauche"},
{en : "turn right", fr : "tourner à droite"},
{en : "go straight", fr : "aller directement"},
{en : "places", fr : "endroits"},
{en : "airport", fr : "l'aéroport"},
{en : "bakery", fr : "la boulangerie"},
{en : "bank", fr : "la banque"},
{en : "beach", fr : "la plage"},
{en : "bookstore", fr : "la librairie"},
{en : "cafe", fr : "le café"},
{en : "church", fr : "l'église"},
{en : "factory", fr : "l'usine"},
{en : "garden", fr : "le jardin"},
{en : "grocery store", fr : "l'épicerie"},
{en : "home", fr : "la maison"},
{en : "hospital", fr : "l'hôpital"},
{en : "library", fr : "la bibliothéque"},
{en : "market", fr : "le marché"},
{en : "movie theater", fr : "le cinéma"},
{en : "museum", fr : "le musée"},
{en : "pastry shop", fr : "la pátisserie"},
{en : "park", fr : "le parc"},
{en : "pharmacy", fr : "la pharmacie"},
{en : "police station", fr : "la gendarmerie"},
{en : "post office", fr : "la poste"},
{en : "pool", fr : "la piscine"},
{en : "restaurant", fr : "le restaurant"},
{en : "school", fr : "l'école"},
{en : "stadium", fr : "le stade"},
{en : "store", fr : "le magasin"},
{en : "train station", fr : "la gare"},
{en : "town hall", fr : "la mairie"},
{en : "zoo", fr : "le zoo"},
{en : "transportation", fr : "transport"},
{en : "by airplane", fr : "en l'avion"},
{en : "by bicycle", fr : "en/a bicyclette"},
{en : "by boat", fr : "en le bateau"},
{en : "by bus", fr : "en l'autobus"},
{en : "by car", fr : "en la voiture"},
{en : "on foot", fr : "à pied"},
{en : "by moped", fr : "en mobylette"},
{en : "by motorcycle", fr : "en la moto"},
{en : "by subway", fr : "en le métro"},
{en : "by taxi", fr : "en le taxi"},
{en : "by train", fr : "en le train"},
{en : "engine", fr : "moteur"},
{en : "wheel", fr : "roue"},
{en : "directions", fr : "indications"},
{en : "family", fr : "la famille"},
{en : "relatives", fr : "des parents"},
{en : "parents", fr : "les parents"},
{en : "mother", fr : "la mère"},
{en : "father", fr : "le père"},
{en : "brother", fr : "le frère"},
{en : "sister", fr : "la sæur"},
{en : "son", fr : "le fils"},
{en : "daughter", fr : "la fille"},
{en : "uncle", fr : "l'oncle"},
{en : "aunt", fr : "la tante"},
{en : "grandmother", fr : "la grand-mère"},
{en : "grandfather", fr : "le grand-père"},
{en : "grandchildren", fr : "les petits-enfants"},
{en : "grandson", fr : "fils"},
{en : "granddaughter", fr : "la petite-fille"},
{en : "niece", fr : "la nièce"},
{en : "nephew", fr : "le neveu"},
{en : "cousin (m/f)", fr : "le cousin/la cousine"},
{en : "husband", fr : "le mari"},
{en : "wife", fr : "la femme"},
{en : "single", fr : "célibataire"},
{en : "married", fr : "mariè(e)"},
{en : "divorced", fr : "divorcè(e)"},
{en : "widow", fr : "veuf/veuve"},
{en : "archer", fr : "l'archer"},
{en : "armor", fr : "l'armure"},
{en : "arrow", fr : "la flèche"},
{en : "axe", fr : "la hache"},
{en : "bow", fr : "l'arc"},
{en : "castle", fr : "le château"},
{en : "cauldron", fr : "la chaudron"},
{en : "demon", fr : "le démon"},
{en : "devil", fr : "le diable"},
{en : "dragon", fr : "le dragon"},
{en : "drawbridge", fr : "le pont-levis"},
{en : "dungeon", fr : "le donjon"},
{en : "dwarf", fr : "le nain"},
{en : "elf", fr : "le lutin"},
{en : "fairy", fr : "la fée"},
{en : "ghost", fr : "le fantôme"},
{en : "giant", fr : "le géant"},
{en : "goblin", fr : "le lutin"},
{en : "king", fr : "le roi"},
{en : "knight", fr : "le chevalier"},
{en : "lance", fr : "la lance"},
{en : "magic", fr : "la magie"},
{en : "mermaid", fr : "la sirène"},
{en : "moat", fr : "les douves"},
{en : "monster", fr : "le monstre"},
{en : "mummy", fr : "la momie"},
{en : "prince/princess", fr : "le prince/la princesse"},
{en : "queen", fr : "le reine"},
{en : "shield", fr : "le bouclier"},
{en : "sword", fr : "l'épée"},
{en : "throne", fr : "le trône"},
{en : "tower", fr : "la tour"},
{en : "unicorn", fr : "la licorne"},
{en : "wizard", fr : "le sorcier"},
{en : "breakfast", fr : "le petit déjeuner"},
{en : "lunch", fr : "le déjeuner"},
{en : "dinner", fr : "le dîner"},
{en : "bowl", fr : "le bol"},
{en : "cup", fr : "la tasse"},
{en : "fork", fr : "la fourchette"},
{en : "knife", fr : "le couteau"},
{en : "plate", fr : "l'assiette"},
{en : "spoon", fr : "la cuillère"},
{en : "beer", fr : "la bière"},
{en : "coffee", fr : "le café"},
{en : "juice", fr : "le jus"},
{en : "milk", fr : "le lait"},
{en : "tea", fr : "le thé"},
{en : "water", fr : "l'eau"},
{en : "wine", fr : "le vin"},
{en : "dessert", fr : "le dessert"},
{en : "ice cream", fr : "la glace"},
{en : "cake", fr : "le gâteau"},
{en : "pie", fr : "la tarte"},
{en : "butter", fr : "le beurre"},
{en : "jam", fr : "la confiture"},
{en : "sugar", fr : "le sucre"},
{en : "salt", fr : "le sel"},
{en : "pepper", fr : "le poivre"},
{en : "soup", fr : "le potage"},
{en : "bread", fr : "le pain"},
{en : "pasta", fr : "des pâtes"},
{en : "cereal", fr : "des céréales"},
{en : "fruit", fr : "un fruit"},
{en : "apple", fr : "une pomme"},
{en : "banana", fr : "une banane"},
{en : "orange", fr : "une orange"},
{en : "grapes", fr : "un raisin"},
{en : "peach", fr : "une pêche"},
{en : "tomato", fr : "une tomate"},
{en : "watermelon", fr : "une pastèque"},
{en : "meat", fr : "la viande"},
{en : "chicken", fr : "le poulet"},
{en : "turkey", fr : "la dinde"},
{en : "ham", fr : "le jambon"},
{en : "fish", fr : "le poisson"},
{en : "egg", fr : "l'æuf"},
{en : "cheese", fr : "le fromage"},
{en : "lettuce", fr : "la laitue"},
{en : "broccoli", fr : "le brocoli"},
{en : "carrot", fr : "une carotte"},
{en : "celery", fr : "un céleri"},
{en : "cucumber", fr : "un concombre"},
{en : "salad", fr : "la salade"},
{en : "house", fr : "la maison"},
{en : "apartment", fr : "l'appartement"},
{en : "room", fr : "la piéce"},
{en : "living room", fr : "le living le salon"},
{en : "kitchen", fr : "la cuisine"},
{en : "dining room", fr : "la salle à manger"},
{en : "hallway", fr : "le couloir"},
{en : "stairs", fr : "l'escalier"},
{en : "bathroom", fr : "la salle de bains"},
{en : "bathtub", fr : "la baignoire"},
{en : "shower", fr : "la douche"},
{en : "sink", fr : "l'évier"},
{en : "roof", fr : "le toit"},
{en : "garage", fr : "le garage"},
{en : "yard", fr : "le jardin"},
{en : "closet", fr : "la penderie"},
{en : "table", fr : "la table"},
{en : "chair", fr : "la chaise"},
{en : "couch", fr : "le canapé/le sofa"},
{en : "desk", fr : "le bureau"},
{en : "window", fr : "la fenêtre"},
{en : "door", fr : "la porte"},
{en : "wall", fr : "mur"},
{en : "bed", fr : "le lit/le plumard"},
{en : "blanket", fr : "la couverture"},
{en : "television", fr : "la télévision"},
{en : "radio", fr : "la radio"},
{en : "refrigerator", fr : "le réfrigérateur"},
{en : "stove", fr : "la cuisiniére"},
{en : "oven", fr : "le four"},
{en : "dishwasher", fr : "le lave-vaisselle"},
{en : "microwave", fr : "le four à micro-ondes"},
{en : "light", fr : "lumière"},
{en : "garbage", fr : "les ordures"},
{en : "angel", fr : "l'ange"},
{en : "baptism", fr : "le baptême"},
{en : "Bible", fr : "la Bible"},
{en : "bishop", fr : "l'évêque"},
{en : "Buddhism", fr : "le bouddhisme"},
{en : "cathedral", fr : "la cathédrale"},
{en : "Christianity", fr : "le christianisme"},
{en : "church", fr : "l'église"},
{en : "faith", fr : "la foi"},
{en : "God", fr : "le Dieu"},
{en : "heaven", fr : "le ciel"},
{en : "hell", fr : "l'enfer"},
{en : "Judaism", fr : "le judaïsme"},
{en : "monastery", fr : "le monastére"},
{en : "Pope", fr : "le pape"},
{en : "prophet", fr : "le prophéte"},
{en : "Protestant", fr : "le protestant"},
{en : "religion", fr : "la religion"},
{en : "sermon", fr : "le sermon"},
{en : "temple", fr : "le temple"},
{en : "worship", fr : "le culte"},
{en : "Accounting", fr : "la comptabilité"},
{en : "Algebra", fr : "l'algébre"},
{en : "Art", fr : "l'art"},
{en : "Biology", fr : "la biologie"},
{en : "Business", fr : "le commerce"},
{en : "Calculus", fr : "le calcul"},
{en : "Chemistry", fr : "la chimie"},
{en : "Computer Science", fr : "l'informatique"},
{en : "Dance", fr : "la danse"},
{en : "Economics", fr : "les sciences économiques"},
{en : "Foreign Languages", fr : "les langues étrangères"},
{en : "Geography", fr : "la géographie"},
{en : "Geometry", fr : "la géométrie"},
{en : "History", fr : "l'histoire"},
{en : "Math", fr : "les mathématiques"},
{en : "Music", fr : "la musique"},
{en : "Physical Education", fr : "l'éducation physique"},
{en : "Physics", fr : "la physique"},
{en : "Political Science", fr : "les sciences politiques"},
{en : "board/chalkboard", fr : "conseil tableau"},
{en : "book", fr : "livre"},
{en : "college", fr : "université"},
{en : "computer", fr : "ordinateur"},
{en : "desk", fr : "bureau"},
{en : "dictionary", fr : "dictionnaire"},
{en : "paper", fr : "papier"},
{en : "pencil", fr : "crayon"},
{en : "pen", fr : "stylo"},
{en : "professor", fr : "le professeur/la professeur"},
{en : "school", fr : "école"},
{en : "student", fr : "l'étudiant/l'étudiante"},
{en : "teacher", fr : "l'instituteur/l'institutrice"},
{en : "test/quiz", fr : "essai/jeu"},
{en : "university", fr : "université"},
{en : "to study", fr : "étudier"},
{en : "to learn", fr : "apprendre"},
{en : "to teach", fr : "enseigner"},
{en : "in", fr : "dans"},
{en : "from, of", fr : "de"},
{en : "well", fr : "bien"},
{en : "she", fr : "elle"},
{en : "if", fr : "si"},
{en : "all", fr : "tout"},
{en : "more", fr : "plus"},
{en : "no", fr : "non"},
{en : "I am", fr : "Je suis"},
{en : "to, at", fr : "à"},
{en : "with", fr : "avec"},
{en : "He goes, is going", fr : "Il va"},
{en : "yes", fr : "oui"},
{en : "He does, makes", fr : "il fait"},
{en : "they", fr : "ils"},
{en : "He has", fr : "Il a"},
{en : "to be", fr : "être"},
{en : "to do, make", fr : "faire"},
{en : "as", fr : "comme"},
{en : "on", fr : "sur"},
{en : "what", fr : "quoi"},
{en : "here", fr : "ici"},
{en : "I know", fr : "Je sais"},
{en : "I want", fr : "Je veux"},
{en : "there", fr : "là"},
{en : "nothing", fr : "rien"},
{en : "He says", fr : "Il dit"},
{en : "You are", fr : "Tu es"},
{en : "where", fr : "où"},
{en : "why", fr : "pourquoi"},
{en : "They are", fr : "Ils sont"},
{en : "when", fr : "quand"},
{en : "by, through", fr : "par"},
{en : "I can", fr : "Je peux"},
{en : "I go, am going", fr : "Je vais"},
{en : "to say", fr : "dire"},
{en : "then", fr : "alors"},
{en : "how", fr : "comment"},
{en : "You have(pl)", fr : "Vous avez"},
{en : "good", fr : "bon"},
{en : "or", fr : "ou"},
{en : "very", fr : "très"},
{en : "thank-you", fr : "merci"},
{en : "They have", fr : "Ils ont"},
{en : "same", fr : "même"},
{en : "never", fr : "jamais"},
{en : "also", fr : "aussi"},
{en : "to see", fr : "voir"},
{en : "thing", fr : "chose"},
{en : "You go (pl)", fr : "Vous allez"},
{en : "all", fr : "tous"},
{en : "these, those", fr : "ces"},
{en : "It is necessary", fr : "Il faut"},
{en : "to be necessary", fr : "falloir"},
{en : "You are (pl)", fr : "Vous êtes"},
{en : "I was", fr : "J'ai été"},
{en : "I do, make", fr : "Je fais"},
{en : "to have", fr : "avoir"},
{en : "He can, is able", fr : "Il peut"},
{en : "other", fr : "autre"},
{en : "again, still", fr : "encore"},
{en : "now", fr : "maintenant"},
{en : "not much, not very", fr : "peu"},
{en : "really", fr : "vraiment"},
{en : "weather, time (m)", fr : "temps"},
{en : "always", fr : "toujours"},
{en : "life", fr : "vie"},
{en : "without", fr : "sans"},
{en : "fair, just", fr : "juste"},
{en : "He had", fr : "Il avait"},
{en : "agreement", fr : "accord"},
{en : "I saw", fr : "J'ai vu"},
{en : "world (m)", fr : "monde"},
{en : "some, any", fr : "quelque"},
{en : "time", fr : "fois"},
{en : "to go", fr : "aller"},
{en : "too much", fr : "trop"},
{en : "I come, am coming", fr : "Je viens"},
{en : "I believe", fr : "Je crois"},
{en : "to believe", fr : "croire"},
{en : "god", fr : "dieu"},
{en : "I have to, I must", fr : "Je dois"},
{en : "to have to", fr : "devoir"},
{en : "man (m)", fr : "homme"},
{en : "father (m)", fr : "père"},
{en : "reliable, safe, certain", fr : "sûr"},
{en : "to the", fr : "aux"},
{en : "before", fr : "avant"},
{en : "I was", fr : "J'étais"},
{en : "woman", fr : "femme"},
{en : "I like, love", fr : "J'aime"},
{en : "person", fr : "personne"},
{en : "I had", fr : "J'avais"},
{en : "TRUE", fr : "vrai"},
{en : "year", fr : "ans"},
{en : "wrong", fr : "mal"},
{en : "to speak", fr : "parler"},
{en : "apres", fr : "après"},
{en : "death", fr : "mort"},
{en : "He wants", fr : "Il veut"},
{en : "I had", fr : "J'ai eu"},
{en : "He will be", fr : "Il sera"},
{en : "because", fr : "parce que"},
{en : "better", fr : "mieux"},
{en : "small", fr : "petit"},
{en : "this, that", fr : "ca"},
{en : "I say, am saying", fr : "Je dis"},
{en : "a lot, much", fr : "beaucoup"},
{en : "since", fr : "depuis"},
{en : "He must", fr : "Il doit"},
{en : "I see", fr : "Je vois"},
{en : "mother", fr : "mère"},
{en : "You go", fr : "Tu vas"},
{en : "sir, Mr, gentleman", fr : "monsieur"},
{en : "what", fr : "quel"},
{en : "already", fr : "déjà"},
{en : "daughter", fr : "fille"},
{en : "people", fr : "gens"},
{en : "so, therefore", fr : "donc"},
{en : "day (m)", fr : "jour"},
{en : "evening (m)", fr : "soir"},
{en : "good morning", fr : "bonjour"},
{en : "house", fr : "maison"},
{en : "name (m)", fr : "nom"},
{en : "money (m)", fr : "argent"},
{en : "I think", fr : "Je pense"},
{en : "to think", fr : "penser"},
{en : "night", fr : "nuit"},
{en : "father", fr : "papa"},
{en : "hi", fr : "salut"},
{en : "that", fr : "cela"},
{en : "We have", fr : "Nous avons"},
{en : "to stay, remain", fr : "rester"},
{en : "I stay, remain", fr : "Je reste"},
{en : "sorry", fr : "désolé"},
{en : "mum", fr : "maman"},
{en : "fright, fear", fr : "peur"},
{en : "to arrive", fr : "arriver"},
{en : "I arrive", fr : "J'arrive"},
{en : "alone, by oneself", fr : "seul"},
{en : "quickly", fr : "vite"},
{en : "to take", fr : "prendre"},
{en : "to look at", fr : "regarder"},
{en : "I look at", fr : "Je regarde"},
{en : "to know", fr : "savoir"},
{en : "less", fr : "moins"},
{en : "son (m)", fr : "fils"},
{en : "between", fr : "entre"},
{en : "low", fr : "bas"},
{en : "head", fr : "tête"},
{en : "tomorrow", fr : "demain"},
{en : "tall, big", fr : "grand"},
{en : "you do, make", fr : "Vous faites"},
{en : "you want", fr : "Vous voulez"},
{en : "to wait for", fr : "attender"},
{en : "I wait for", fr : "J'attends"},
{en : "child", fr : "enfant"},
{en : "enough", fr : "assez"},
{en : "reason", fr : "raison"},
{en : "I would have", fr : "J'aurais"},
{en : "I would like", fr : "Je voulais"},
{en : "I speak", fr : "Je parle"},
{en : "moment (m)", fr : "moment"},
{en : "hour", fr : "heure"},
{en : "then", fr : "puis"},
{en : "love (m)", fr : "amour"},
{en : "late", fr : "tard"},
{en : "We are", fr : "Nous sommes"},
{en : "to kill", fr : "tuer"},
{en : "friend (m)", fr : "ami"},
{en : "I know", fr : "Je connais"},
{en : "to know", fr : "connaitre"},
{en : "to help", fr : "aider"},
{en : "luck, fortune", fr : "chance"},
{en : "You know", fr : "Vous savez"},
{en : "to leave, to go", fr : "partir"},
{en : "He knows", fr : "Il sait"},
{en : "how much", fr : "combien"},
{en : "car", fr : "voiture"},
{en : "I took", fr : "J'ai pris"},
{en : "He leaves", fr : "Il part"},
{en : "problem (m)", fr : "problème"},
{en : "I take", fr : "Je prends"},
{en : "to carry", fr : "porter"},
{en : "I carry", fr : "Je porte"},
{en : "to open", fr : "ouvrir"},
{en : "He would be", fr : "Il serait"},
{en : "to come", fr : "venir"},
{en : "today", fr : "aujourd'hui"},
{en : "famille", fr : "famille"},
{en : "last", fr : "dernier"},
{en : "work (m)", fr : "travail"},
{en : "I could", fr : "J'ai pu"},
{en : "We go, are going", fr : "Nous allons"},
{en : "goodbye", fr : "au revoir"},
{en : "idea", fr : "idée"},
{en : "to cross, go through", fr : "passer"},
{en : "against", fr : "contre"},
{en : "to understand", fr : "comprendre"},
{en : "I understand", fr : "Je comprends"},
{en : "I heard", fr : "J'ai entendu"},
{en : "I found", fr : "J'ai trouvé"},
{en : "to find", fr : "trouver"},
{en : "old", fr : "vieux"},
{en : "He comes", fr : "Il vient"},
{en : "He could have", fr : "il aurait"},
{en : "some", fr : "quelques"},
{en : "attention", fr : "attention"},
{en : "to ask for", fr : "demander"},
{en : "I ask for", fr : "Je demande"},
{en : "to look for", fr : "chercher"},
{en : "under", fr : "sous"},
{en : "here is", fr : "voici"},
{en : "He could", fr : "Il pourrait"},
{en : "blood (m)", fr : "sang"},
{en : "You can (pl)", fr : "Vous pouvez"},
{en : "to go out, to take out", fr : "sortir"},
{en : "question", fr : "question"},
{en : "history", fr : "histoire"},
{en : "door", fr : "porte"},
{en : "friends", fr : "amis"},
{en : "You come, are coming", fr : "Vous venez"},
{en : "brother (m)", fr : "frère"},
{en : "to stay, remain", fr : "rester"},
{en : "I finished", fr : "J'ai fini"},
{en : "town", fr : "ville"},
{en : "new", fr : "nouveau"},
{en : "knack, trick (m)", fr : "truc"},
{en : "month (m)", fr : "mois"},
{en : "bloke, chap (m)", fr : "mec"},
{en : "eyes", fr : "yeux"},
{en : "to leave", fr : "laisser"},
{en : "beautiful", fr : "beau"},
{en : "a long time", fr : "longtemps"},
{en : "water", fr : "eau"},
{en : "because, for", fr : "car"},
{en : "case (m)", fr : "cas"},
{en : "they go, are going", fr : "ils vont"},
{en : "each, every", fr : "chaque"},
{en : "place", fr : "place"},
{en : "hand", fr : "main"},
{en : "sorry", fr : "pardon"},
{en : "together", fr : "ensemble"},
{en : "only", fr : "seulement"},
{en : "war", fr : "guerre"},
{en : "towards", fr : "vers"},
{en : "in front of", fr : "devant"},
{en : "I find", fr : "Je trouve"},
{en : "part", fr : "partie"},
{en : "I understood", fr : "J'ai compris"},
{en : "morning (m)", fr : "matin"},
{en : "I arrived", fr : "Je suis arrivé"},
{en : "upper", fr : "dessus"},
{en : "to put", fr : "mettre"},
{en : "They were", fr : "Ils étaient"},
{en : "to lose", fr : "perdre"},
{en : "I lost", fr : "J'ai perdu"},
{en : "during", fr : "pendant"},
{en : "first", fr : "premier"},
{en : "sort, kind, type of", fr : "genre"},
{en : "straight, law, right", fr : "droit"},
{en : "I give", fr : "Je donne"},
{en : "You wait (pl)", fr : "Vous attendez"},
{en : "young", fr : "jeune"},
{en : "fire (m)", fr : "feu"},
{en : "I should", fr : "Je devrais"},
{en : "room", fr : "chambre"},
{en : "coast, side", fr : "côté"},
{en : "I came", fr : "Je suis venu"},
{en : "to write", fr : "écrire"},
{en : "a long way, far", fr : "loin"},
{en : "to leave", fr : "laisser"},
{en : "to remind", fr : "rappeler"},
{en : "to go up", fr : "monter"},
{en : "to give", fr : "donner"},
{en : "to play", fr : "jouer"},
{en : "I knew", fr : "Je savais"},
{en : "I spoke", fr : "J'ai parlé"},
{en : "minute", fr : "minute"},
{en : "madam, Mrs", fr : "madame"},
{en : "You look at (pl)", fr : "Vous regardez"},
{en : "train (m)", fr : "train"},
{en : "to be able", fr : "pouvoir"},
{en : "He will have", fr : "Il aura"},
{en : "to die", fr : "mourir"},
{en : "last", fr : "dernière"},
{en : "I gave", fr : "J'ai donné"},
{en : "husband (m)", fr : "mari"},
{en : "I listen to", fr : "J'écoute"},
{en : "finally", fr : "enfin"},
{en : "He would have", fr : "Il devrait"},
{en : "I put", fr : "J'ai mis"},
{en : "strong", fr : "fort"},
{en : "way", fr : "façon"},
{en : "country (m)", fr : "pays"},
{en : "ready", fr : "prêt"},
{en : "affair, matter, business", fr : "affaire"},
{en : "I would be able", fr : "Je pourrais"},
{en : "I hope", fr : "J'espère"},
{en : "I left", fr : "Je suis parti"},
{en : "place (m)", fr : "endroit"},
{en : "mad", fr : "fou"},
{en : "body (m)", fr : "corps"},
{en : "yesterday", fr : "hier"},
{en : "sorry", fr : "désolée"},
{en : "point (m)", fr : "point"},
{en : "outside", fr : "dehors"},
{en : "to live", fr : "vivre"},
{en : "close", fr : "près"},
{en : "I thought", fr : "Je pensais"},
{en : "boy (m)", fr : "garçon"},
{en : "leader, boss (m)", fr : "chef"},
{en : "high", fr : "haut"},
{en : "captain (m)", fr : "capitaine"},
{en : "He would say", fr : "Il dirait"},
{en : "baby (m)", fr : "bébé"},
{en : "I asked", fr : "J'ai demandé"},
{en : "possible", fr : "possible"},
{en : "thus, so", fr : "ainsi"},
{en : "full, whole", fr : "plein"},
{en : "to tell", fr : "raconteur"},
{en : "week", fr : "semaine"},
{en : "You say (pl)", fr : "Vous dites"},
{en : "to believe", fr : "croire"},
{en : "to walk", fr : "marcher"},
{en : "I walk", fr : "Je marche"},
{en : "school", fr : "école"},
{en : "to eat", fr : "manger"},
{en : "rather", fr : "plutôt"},
{en : "doctor (m)", fr : "docteur"},
{en : "truth", fr : "vérité"},
{en : "view, sight", fr : "vue"},
{en : "to stop", fr : "arrêter"},
{en : "I try", fr : "J'essaie"},
{en : "to try", fr : "essayer"},
{en : "to send", fr : "envoyer"},
{en : "I send", fr : "J'envie"},
{en : "soon", fr : "bientôt"},
{en : "a moment, instant (m)", fr : "instant"},
{en : "to arrive", fr : "arriver"},
{en : "to ask for", fr : "demander"},
{en : "better", fr : "meilleur"},
{en : "They do, make", fr : "Ils font"},
{en : "behind", fr : "derrière"},
{en : "almost, nearly", fr : "presque"},
{en : "so, so much", fr : "tellement"},
{en : "to fall", fr : "tomber"},
{en : "day", fr : "journée"},
{en : "He wants", fr : "Il voulait"},
{en : "to call", fr : "appeler"},
{en : "office (m)", fr : "bureau"},
{en : "trust", fr : "confiance"},
{en : "guard (m)", fr : "garde"},
{en : "to wait for", fr : "attendre"},
{en : "number (m)", fr : "numéro"},
{en : "I will be", fr : "Je serai"},
{en : "hard, tough", fr : "dur"},
{en : "to remember", fr : "souvenir"},
{en : "You see", fr : "Vous voyez"},
{en : "lesson, class (m)", fr : "cours"},
{en : "good evening", fr : "bonsoir"},
{en : "road", fr : "route"},
{en : "He will do,make", fr : "Il fera"},
{en : "He takes", fr : "Il prend"},
{en : "important", fr : "important"},
{en : "sorrow, grief", fr : "peine"},
{en : "I believed", fr : "Je croyais"},
{en : "word (m)", fr : "mot"},
{en : "You have to,must (pl)", fr : "Vous devez"},
{en : "to close", fr : "fermer"},
{en : "I close", fr : "Je ferme"},
{en : "pleasure (m)", fr : "plaisir"},
{en : "dog (m)", fr : "chien"},
{en : "game (m)", fr : "jeu"},
{en : "calm, still", fr : "calme"},
{en : "I would like", fr : "Je voudrais"},
{en : "happy", fr : "heureux"},
{en : "You take", fr : "Vous prenez"},
{en : "marriage (m)", fr : "mariage"},
{en : "He sees", fr : "Il voit"},
{en : "inside", fr : "dedans"},
{en : "to get in, to enter", fr : "entrer"},
{en : "bed (m)", fr : "lit"},
{en : "perfect", fr : "parfait"},
{en : "to get back, come back", fr : "rentrer"},
{en : "music", fr : "musique"},
{en : "You stop", fr : "Vous arrêtez"},
{en : "as much", fr : "autant"},
{en : "service, favour (m)", fr : "service"},
{en : "this", fr : "ceci"},
{en : "odd, funny", fr : "drôle"},
{en : "He waits", fr : "Il attend"},
{en : "sometimes", fr : "parfois"},
{en : "phone (m)", fr : "téléphone"},
{en : "return (m)", fr : "retour"},
{en : "He will go", fr : "Il ira"},
{en : "poor", fr : "pauvre"},
{en : "glass (m)", fr : "verre"},
{en : "I thought", fr : "J'ai pensé"},
{en : "impossible", fr : "impossible"},
{en : "holiday, party", fr : "fête"},
{en : "I adore, love", fr : "J'adore"},
{en : "heart (m)", fr : "coeur"},
{en : "You like, love", fr : "Tu aimes"},
{en : "président (m)", fr : "président"},
{en : "doubt (m)", fr : "doute"},
{en : "easy", fr : "facile"},
{en : "I hear", fr : "J'entends"},
{en : "to pay", fr : "payer"},
{en : "prisión", fr : "prison"},
{en : "I go out, take out", fr : "Je sors"},
{en : "coffee (m)", fr : "café"},
{en : "bad", fr : "mauvais"},
{en : "to forget", fr : "oublier"},
{en : "I forgot", fr : "J'ai oublié"},
{en : "arm (m)", fr : "bras"},
{en : "kind, nice", fr : "gentil"},
{en : "team (m)", fr : "équipe"},
{en : "exactly", fr : "exactement"},
{en : "to change", fr : "changer"},
{en : "I begin, start", fr : "Je commence"},
{en : "place (m)", fr : "lieu"},
{en : "king (m)", fr : "roi"},
{en : "map, plan (m)", fr : "plan"},
{en : "everywhere", fr : "partout"},
{en : "expensive", fr : "cher"},
{en : "to give back, return", fr : "rendre"},
{en : "I wrote", fr : "J'ai écrit"},
{en : "to work", fr : "travailler"},
{en : "ill, sick", fr : "malade"},
{en : "otherwise, or else", fr : "sinon"},
{en : "great, brilliant", fr : "génial"},
{en : "They want", fr : "Ils veulent"},
{en : "I work", fr : "Je travaille"},
{en : "army", fr : "armée"},
{en : "I wanted", fr : "J'ai voulu"},
{en : "I look for", fr : "Je cherche"},
{en : "state, nation (m)", fr : "état"},
{en : "to drink", fr : "boire"},
{en : "year", fr : "année"},
{en : "I left", fr : "J'ai laissé"},
{en : "wood (m)", fr : "bois"},
{en : "I put", fr : "Je mets"},
{en : "clean", fr : "propre"},
{en : "early", fr : "tôt"},
{en : "above all", fr : "surtout"},
{en : "dream (m)", fr : "rêve"},
{en : "worse", fr : "pire"},
{en : "simple, plain", fr : "simple"},
{en : "You think", fr : "Tu penses"},
{en : "You speak", fr : "Tu parles"},
{en : "peace", fr : "paix"},
{en : "book (m)", fr : "livre"},
{en : "to sleep", fr : "dormir"},
{en : "We see", fr : "Nous voyons"},
{en : "difficult", fr : "difficile"},
{en : "He went", fr : "Il allait"},
{en : "subject (m)", fr : "sujet"},
{en : "I learnt", fr : "J'ai appris"},
{en : "then, later", fr : "ensuite"},
{en : "except", fr : "sauf"},
{en : "black", fr : "noir"},
{en : "to have dinner", fr : "dîner"},
{en : "choice (m)", fr : "choix"},
{en : "I would be", fr : "Je serais"},
{en : "dirty", fr : "sale"},
{en : "You were", fr : "Vous étiez"},
{en : "surely", fr : "sûrement"},
{en : "year (m)", fr : "an"},
{en : "order (m)", fr : "ordre"},
{en : "often", fr : "souvent"},
{en : "to win", fr : "gagner"},
{en : "They are able", fr : "Ils peuvent"},
{en : "to sell", fr : "vendre"},
{en : "advice", fr : "le conseil"},
{en : "junior high school", fr : "le collège"},
{en : "key", fr : "la clé"},
{en : "blow, knock, shock", fr : "le coup"},
{en : "lunch", fr : "le déjeuner"},
{en : "heart", fr : "le coeur"},
{en : "tights", fr : "les collants"},
{en : "necklace", fr : "le collier"},
{en : "colors", fr : "les couleurs"},
{en : "supermarket", fr : "le supermarché"},
{en : "museum", fr : "le musée"},
{en : "jam", fr : "la confiture"},
{en : "pig", fr : "le cochon"},
{en : "decade", fr : "la décennie"},
{en : "the dates", fr : "les dates"},
{en : "women's underpants", fr : "la culotte"},
{en : "dance", fr : "la danse"},
{en : "December", fr : "décembre"},
{en : "lady", fr : "la dame"},
{en : "lemon", fr : "le citron"},
{en : "friend", fr : "le copain/la copine"},
{en : "dresser", fr : "la commode"},
{en : "suit", fr : "le complet"},
{en : "essay", fr : "la composition"},
{en : "veal", fr : "le veau"},
{en : "spoon", fr : "la cuillère"},
{en : "shellfish", fr : "les crustacés"},
{en : "cross", fr : "la croix"},
{en : "dusk", fr : "le crépuscule"},
{en : "shrimp", fr : "la crevette"},
{en : "tie", fr : "la cravate"},
{en : "pencil", fr : "le crayon"},
{en : "cream", fr : "la crème"},
{en : "skull", fr : "le crâne"},
{en : "blanket", fr : "la couverture"},
{en : "knife", fr : "le couteau"},
{en : "courtyard", fr : "la cour"},
{en : "mail", fr : "le courrier"},
{en : "class", fr : "le cours"},
{en : "cousin", fr : "le cousin/la cousine"},
{en : "living room", fr : "le salon"},
{en : "seasons", fr : "les saisons"},
{en : "dress", fr : "la robe"},
{en : "reason", fr : "la raison"},
{en : "dream", fr : "la rêve"},
{en : "Miss", fr : "Mademoiselle"},
{en : "job", fr : "le métier"},
{en : "forecast", fr : "la météo"},
{en : "mother", fr : "la mère"},
{en : "music", fr : "la musique"},
{en : "snow", fr : "la neige"},
{en : "restaurant", fr : "le restaurant"},
{en : "information", fr : "les rensignements"},
{en : "appointment", fr : "le rendez-vous"},
{en : "essay", fr : "la rédaction"},
{en : "razor", fr : "le rasoir"},
{en : "tea", fr : "le thé"},
{en : "answer", fr : "la réponse"},
{en : "street", fr : "la rue"},
{en : "bag", fr : "le sac"},
{en : "question", fr : "la question"},
{en : "salad", fr : "la salade"},
{en : "blood", fr : "le sang"},
{en : "cold", fr : "le rhume"},
{en : "hall", fr : "la salle"},
{en : "car", fr : "la voiture"},
{en : "lane", fr : "la voie"},
{en : "reading", fr : "la lecture"},
{en : "class", fr : "la leçon"},
{en : "bed", fr : "le lit"},
{en : "literature", fr : "la littérature"},
{en : "hand", fr : "la main"},
{en : "dishwasher", fr : "le lave-vaisselle"},
{en : "sink", fr : "le lavabo"},
{en : "rabbit", fr : "le lapin"},
{en : "location", fr : "le lieu"},
{en : "bookstore", fr : "la librairie"},
{en : "letter", fr : "la lettre"},
{en : "lettuce", fr : "la laitue"},
{en : "lip", fr : "la lèvre"},
{en : "language", fr : "la langue"},
{en : "milk", fr : "le lait"},
{en : "vegetables", fr : "les légumes"},
{en : "police station", fr : "le commissariat"},
{en : "heel", fr : "le talon"},
{en : "movie theater", fr : "le cinéma"},
{en : "neck", fr : "le cou"},
{en : "elbow", fr : "le coude"},
{en : "body", fr : "le corps"},
{en : "suit", fr : "le costume"},
{en : "coast", fr : "la côte"},
{en : "side", fr : "le côté"},
{en : "driver", fr : "le conducteur"},
{en : "concert", fr : "le concert"},
{en : "kitchen", fr : "la cuisine"},
{en : "chocolate", fr : "le chocolat"},
{en : "dog", fr : "le chien"},
{en : "thigh", fr : "la cuisse"},
{en : "sky", fr : "le ciel"},
{en : "scar", fr : "la cicatrice"},
{en : "leather", fr : "le cuir"},
{en : "circus", fr : "le cirque"},
{en : "grade level", fr : "la classe"},
{en : "grade", fr : "la note"},
{en : "glass", fr : "le verre"},
{en : "theatre", fr : "le théâtre"},
{en : "high school student", fr : "le lycéen/la lycénne"},
{en : "Missus", fr : "Madame"},
{en : "moon", fr : "la lune"},
{en : "glasses", fr : "les lunettes"},
{en : "high school", fr : "le lycée"},
{en : "book", fr : "le livre"},
{en : "coat", fr : "le manteau"},
{en : "makeup", fr : "le maquillage"},
{en : "market", fr : "le marché"},
{en : "husband", fr : "le mari"},
{en : "wedding", fr : "le mariage"},
{en : "head", fr : "la tête"},
{en : "rug", fr : "le tapis"},
{en : "October", fr : "octobre"},
{en : "minute", fr : "la minute"},
{en : "mirror", fr : "le miroir"},
{en : "news", fr : "la nouvelle"},
{en : "November", fr : "novembre"},
{en : "cloud", fr : "le nuage"},
{en : "train", fr : "le train"},
{en : "night", fr : "la nuit"},
{en : "numbers", fr : "les numéros"},
{en : "bird", fr : "l'oiseau"},
{en : "uncle", fr : "l'oncle"},
{en : "nail", fr : "l'ongle"},
{en : "storm", fr : "l'orage"},
{en : "orange", fr : "l'orange"},
{en : "ear", fr : "l'oreille"},
{en : "Sir", fr : "Monsieur"},
{en : "world", fr : "le monde"},
{en : "month", fr : "le mois"},
{en : "corn", fr : "le maïs"},
{en : "house", fr : "la maison"},
{en : "eye", fr : "l'oeil"},
{en : "furniture", fr : "les meubles"},
{en : "grape", fr : "le raisin"},
{en : "meal", fr : "le repas"},
{en : "stamp", fr : "le timbre"},
{en : "dining room", fr : "la salle à manger"},
{en : "bathroom", fr : "la salle de bains"},
{en : "voice", fr : "la voix"},
{en : "tail", fr : "la queue"},
{en : "sandwich", fr : "le sandwich"},
{en : "fever", fr : "la fièvre"},
{en : "cheese", fr : "le fromage"},
{en : "thread", fr : "le fil"},
{en : "forehead", fr : "le front"},
{en : "fruits", fr : "les fruits"},
{en : "kid", fr : "le gamin"},
{en : "gloves", fr : "les gants"},
{en : "garage", fr : "le garage"},
{en : "boy", fr : "le garçon"},
{en : "station", fr : "la gare"},
{en : "cake", fr : "le gâteau"},
{en : "snail", fr : "l'escargot"},
{en : "floor", fr : "le plancher"},
{en : "rain", fr : "la pluie"},
{en : "map", fr : "le plan"},
{en : "silk", fr : "la soie"},
{en : "granddaughter", fr : "la petite-fille"},
{en : "plate", fr : "le plat"},
{en : "lake", fr : "le lac"},
{en : "men's briefs", fr : "le slip"},
{en : "forest", fr : "la forêt"},
{en : "lighting", fr : "la foudre"},
{en : "oven", fr : "le four"},
{en : "mix", fr : "le mélange"},
{en : "wall", fr : "le mur"},
{en : "swimming", fr : "la natation"},
{en : "household", fr : "ménage"},
{en : "bicycle", fr : "le vélo"},
{en : "birth", fr : "la naissance"},
{en : "watch", fr : "la montre"},
{en : "sea", fr : "la mer"},
{en : "death", fr : "la mort"},
{en : "word", fr : "le mot"},
{en : "sheep", fr : "le mouton"},
{en : "moustache", fr : "la moustache"},
{en : "chin", fr : "le menton"},
{en : "subway", fr : "le métro"},
{en : "mountain", fr : "la montagne"},
{en : "walnut", fr : "la noix"},
{en : "doctor", fr : "le médecin"},
{en : "morning", fr : "le matin"},
{en : "bathing suit", fr : "le maillot de bain"},
{en : "May", fr : "mai"},
{en : "job", fr : "l'ouvrage"},
{en : "opening", fr : "une ouverture"},
{en : "niece", fr : "la nièce"},
{en : "nose", fr : "le nez"},
{en : "nephew", fr : "le neveu"},
{en : "size", fr : "la taille"},
{en : "west", fr : "ouest"},
{en : "telephone", fr : "le téléphone"},
{en : "middle", fr : "le milieu"},
{en : "microwave", fr : "le micro-ondes"},
{en : "subjects", fr : "les matières"},
{en : "egg", fr : "l'oeuf"},
{en : "math", fr : "les maths"},
{en : "mattress", fr : "le matelas"},
{en : "March", fr : "mars"},
{en : "onion", fr : "l'oignon"},
{en : "work of art", fr : "l'oeuvre"},
{en : "illness", fr : "la maladie"},
{en : "mom", fr : "la maman"},
{en : "sleeve", fr : "la manche"},
{en : "pillow", fr : "l'oreiller"},
{en : "bone", fr : "l'os"},
{en : "medicine", fr : "le médicament"},
{en : "last name", fr : "le nom"},
{en : "north", fr : "le nord"},
{en : "share", fr : "la part"},
{en : "step", fr : "le pas"},
{en : "passenger", fr : "le passager"},
{en : "country", fr : "le pays"},
{en : "past", fr : "le passé"},
{en : "wrist", fr : "le poignet"},
{en : "fish", fr : "le poisson"},
{en : "chest", fr : "la poitrine"},
{en : "juice", fr : "le jus"},
{en : "pepper", fr : "le poivre"},
{en : "apple", fr : "la pomme"},
{en : "pork", fr : "le porc"},
{en : "skirt", fr : "la jupe"},
{en : "bread", fr : "le pain"},
{en : "student", fr : "l'étudiant"},
{en : "son", fr : "le fils"},
{en : "end", fr : "la fin"},
{en : "company", fr : "la firme"},
{en : "flower", fr : "la fleur"},
{en : "river", fr : "le fleuve"},
{en : "liver", fr : "le foie"},
{en : "daughter", fr : "la fille"},
{en : "animals", fr : "les animaux"},
{en : "August", fr : "août"},
{en : "department", fr : "la faculté"},
{en : "fencing", fr : "l'escrime"},
{en : "Spanish", fr : "l'espagnol"},
{en : "hunger", fr : "la faim"},
{en : "friend", fr : "l'ami"},
{en : "cash", fr : "les espèces"},
{en : "family", fr : "la famille"},
{en : "armchair", fr : "le fauteuil"},
{en : "wife", fr : "la femme"},
{en : "farm", fr : "la ferme"},
{en : "spirit", fr : "l'esprit"},
{en : "company", fr : "l'entreprise"},
{en : "grocery store", fr : "l'épicerie"},
{en : "spinach", fr : "les épinards"},
{en : "spouse", fr : "l'épouse"},
{en : "weather", fr : "le temps"},
{en : "spouse (m)", fr : "l'époux"},
{en : "stairs", fr : "l'escalier"},
{en : "college", fr : "l'université"},
{en : "experiment", fr : "l'essai"},
{en : "gas", fr : "l'essence"},
{en : "child", fr : "l'enfant"},
{en : "east", fr : "l'est"},
{en : "stomach", fr : "l'estomac"},
{en : "level", fr : "l'étage"},
{en : "summer", fr : "l'été"},
{en : "star", fr : "l'étoile"},
{en : "test", fr : "l'examen"},
{en : "soccer", fr : "le foot"},
{en : "football", fr : "le football américain"},
{en : "party", fr : "la fête"},
{en : "holidays", fr : "les fêtes"},
{en : "fire", fr : "le feu"},
{en : "leaf", fr : "la feuille"},
{en : "February", fr : "février"},
{en : "engagement", fr : "les fiançailles"},
{en : "skin", fr : "la peau"},
{en : "comb", fr : "le peigne"},
{en : "lawn", fr : "la pelouse"},
{en : "bell", fr : "la sonnette"},
{en : "device", fr : "l'appareil"},
{en : "apartment", fr : "l'appartement"},
{en : "cow", fr : "la vache"},
{en : "health", fr : "la santé"},
{en : "thirst", fr : "la soif"},
{en : "waiter", fr : "le serveur"},
{en : "waitress", fr : "la serveuse"},
{en : "supper", fr : "le souper"},
{en : "eyebrow", fr : "le sourcil"},
{en : "soap", fr : "le savon"},
{en : "science", fr : "la science"},
{en : "evening", fr : "le soir"},
{en : "tennis", fr : "le tennis"},
{en : "century", fr : "le siècle"},
{en : "monkey", fr : "le singe"},
{en : "September", fr : "septembre"},
{en : "skiing", fr : "le ski"},
{en : "being", fr : "l'être"},
{en : "English", fr : "l'anglais"},
{en : "meat", fr : "la viande"},
{en : "father", fr : "le père"},
{en : "boyfriend", fr : "le petit ami"},
{en : "breakfast", fr : "le petit déjeuner"},
{en : "girlfriend", fr : "la petite amie"},
{en : "peace", fr : "la paix"},
{en : "foot", fr : "le pied"},
{en : "hobby", fr : "le passe-temps"},
{en : "grapefruit", fr : "le pamplemousse"},
{en : "pants", fr : "le pantalon"},
{en : "slippers", fr : "les pantoufles"},
{en : "dad", fr : "le papa"},
{en : "pool", fr : "la piscine"},
{en : "paper", fr : "le papier"},
{en : "umbrella", fr : "le parapluie"},
{en : "park", fr : "le parc"},
{en : "parents", fr : "les parents"},
{en : "watermelon", fr : "la pastèque"},
{en : "boss", fr : "le patron/la patronne"},
{en : "trip", fr : "le voyage"},
{en : "pen", fr : "le stylo"},
{en : "banana", fr : "la banane"},
{en : "bank", fr : "la banque"},
{en : "afternoon", fr : "l'après-midi"},
{en : "tree", fr : "l'arbre"},
{en : "sport", fr : "le sport"},
{en : "belly", fr : "le ventre"},
{en : "rainbow", fr : "l'arc-en-ciel"},
{en : "zero", fr : "le zéro"},
{en : "bill", fr : "l'addition"},
{en : "airport", fr : "l'aéroport"},
{en : "wound", fr : "la blessure"},
{en : "bathtub", fr : "la baignoire"},
{en : "kiss", fr : "le baiser"},
{en : "garlic", fr : "l'ail"},
{en : "lawyer", fr : "l'avocat/l'avocate"},
{en : "April", fr : "avril"},
{en : "luggage", fr : "le bagage"},
{en : "ring", fr : "la bague"},
{en : "money", fr : "l'argent"},
{en : "closet", fr : "l'armoire"},
{en : "south", fr : "le sud"},
{en : "box", fr : "la boîte"},
{en : "beverage", fr : "la boisson"},
{en : "father-in-law", fr : "le beau-père"},
{en : "balcony", fr : "le balcon"},
{en : "boat", fr : "le bateau"},
{en : "blackboard", fr : "le tableau noir"},
{en : "thunder", fr : "le tonnerre"},
{en : "painting", fr : "le tableau"},
{en : "woman's suit", fr : "le tailleur"},
{en : "beef", fr : "le boeuf"},
{en : "table", fr : "la table"},
{en : "foods", fr : "les aliments"},
{en : "kindness", fr : "la bonté"},
{en : "boots", fr : "les bottes"},
{en : "mouth", fr : "la bouche"},
{en : "bakery", fr : "la boulangerie"},
{en : "arm", fr : "le bras"},
{en : "brush", fr : "la brosse"},
{en : "plum", fr : "la prune"},
{en : "sweater", fr : "le pull"},
{en : "desk", fr : "le pupitre"},
{en : "pajamas", fr : "le pyjama"},
{en : "vacation", fr : "les vacances"},
{en : "pocket", fr : "la poche"},
{en : "seat", fr : "la place"},
{en : "ceiling", fr : "le plafond"},
{en : "sister", fr : "la soeur"},
{en : "price", fr : "le prix"},
{en : "professor", fr : "le prof"},
{en : "teacher", fr : "le professeur"},
{en : "jacket", fr : "le veston"},
{en : "post office", fr : "la poste"},
{en : "thumb", fr : "le pouce"},
{en : "chicken", fr : "le poulet"},
{en : "lung", fr : "le poumon"},
{en : "wallet", fr : "le portefeuille"},
{en : "blouse", fr : "le chemisier"},
{en : "mall", fr : "le centre commercial"},
{en : "suitcase", fr : "a valise"},
{en : "cereal", fr : "la céréale"},
{en : "cherry", fr : "la cerise"},
{en : "brain", fr : "le cerveau"},
{en : "chair", fr : "la chaise"},
{en : "song", fr : "la chanson"},
{en : "notebook", fr : "le carnet"},
{en : "hat", fr : "le chapeau"},
{en : "cat", fr : "le chat"},
{en : "castle", fr : "le château"},
{en : "office", fr : "le bureau"},
{en : "peanut", fr : "la cacahuète"},
{en : "gift", fr : "le cadeau"},
{en : "coffee", fr : "le café"},
{en : "check", fr : "le chèque"},
{en : "driver", fr : "le chauffeur"},
{en : "socks", fr : "les chaussettes"},
{en : "shoes", fr : "les chaussures"},
{en : "shirt", fr : "la chemise"},
{en : "bedroom", fr : "la chambre"},
{en : "autumn", fr : "l'automne"},
{en : "sugar", fr : "le sucre"},
{en : "basketball", fr : "le basket"},
{en : "sneakers", fr : "les baskets"},
{en : "beard", fr : "la barbe"},
{en : "baseball", fr : "le base-ball"},
{en : "everybody", fr : "tout le monde"},
{en : "bar", fr : "le bar"},
{en : "flight", fr : "le vol"},
{en : "poultry", fr : "la volaille"},
{en : "ticket", fr : "le billet"},
{en : "daughter-in-law", fr : "la belle-fille"},
{en : "mother-in-law", fr : "la belle-mère"},
{en : "need", fr : "le besoin"},
{en : "butter", fr : "le beurre"},
{en : "library", fr : "la bibliothèque"},
{en : "bicycle", fr : "la bicyclette"},
{en : "art", fr : "l'art"},
{en : "city", fr : "la ville"},
{en : "wine", fr : "le vin"},
{en : "vacuum", fr : "l'aspirateur"},
{en : "plate", fr : "l'assiette"},
{en : "cookie", fr : "le biscuit"},
{en : "baby", fr : "le bébé"},
{en : "today", fr : "aujourd'hui"},
{en : "diamond", fr : "le diamant"},
{en : "turkey", fr : "la dinde"},
{en : "dinner", fr : "le dîner"},
{en : "entertainment", fr : "le divertissement"},
{en : "drawing", fr : "le dessin"},
{en : "toilet", fr : "les toilettes"},
{en : "tooth", fr : "la dent"},
{en : "departure", fr : "le départ"},
{en : "water", fr : "l'eau"},
{en : "scarf", fr : "l'écharpe"},
{en : "school", fr : "l'école"},
{en : "dessert", fr : "le dessert"},
{en : "homework", fr : "les devoirs"},
{en : "finger", fr : "le doigt"},
{en : "back", fr : "le dos"},
{en : "life", fr : "la vie"},
{en : "truth", fr : "la vérité"},
{en : "shower", fr : "la douche"},
{en : "field", fr : "le champ"},
{en : "fog", fr : "le brouillard"},
{en : "horse", fr : "le cheval"},
{en : "hair", fr : "les cheveux"},
{en : "ankle", fr : "la cheville"},
{en : "clothing", fr : "les vêtements"},
{en : "countryside", fr : "la campagne"},
{en : "cafeteria", fr : "la cantine"},
{en : "mushroom", fr : "le champignon"},
{en : "couch", fr : "le canapé"},
{en : "duck", fr : "le canard"},
{en : "carrot", fr : "la carrotte"},
{en : "intersection", fr : "le carrefour"},
{en : "menu", fr : "la carte"},
{en : "belt", fr : "la ceinture"},
{en : "fork", fr : "la fourchette"},
{en : "fur", fr : "la fourrure"},
{en : "stay", fr : "le séjour"},
{en : "snake", fr : "le serpent"},
{en : "cheek", fr : "la joue"},
{en : "days", fr : "les jours"},
{en : "July", fr : "juillet"},
{en : "June", fr : "juin"},
{en : "show", fr : "le spectacle"},
{en : "twin", fr : "le jumeau/la jumelle"},
{en : "salt", fr : "le sel"},
{en : "week", fr : "la semaine"},
{en : "party", fr : "la soirée"},
{en : "spring", fr : "le printemps"},
{en : "boredom", fr : "l'ennui"},
{en : "year", fr : "l'an"},
{en : "pineapple", fr : "l'ananas"},
{en : "sun", fr : "le soleil"},
{en : "dream", fr : "le songe"},
{en : "grandson", fr : "le petit-fils"},
{en : "French", fr : "le français"},
{en : "brother", fr : "le frère"},
{en : "raspberry", fr : "la framboise"},
{en : "refrigerator", fr : "le frigo"},
{en : "movie", fr : "le film"},
{en : "entrance", fr : "l'entrée"},
{en : "room", fr : "la pièce"},
{en : "grandchildren", fr : "les petits-enfants"},
{en : "door", fr : "la porte"},
{en : "first name", fr : "le prénom"},
{en : "sentence", fr : "la phrase"},
{en : "strawberry", fr : "la fraise"},
{en : "breast", fr : "le sein"},
{en : "television set", fr : "le téléviseur"},
{en : "grandmother", fr : "la grand-mère"},
{en : "grandfather", fr : "le grand-père"},
{en : "leg", fr : "la jambe"},
{en : "January", fr : "janvier"},
{en : "garden", fr : "le jardin"},
{en : "game", fr : "le jeu"},
{en : "basement", fr : "le sous-sol"},
{en : "direction", fr : "l'indication"},
{en : "nurse", fr : "l'infirmier/l'infirmière"},
{en : "drops", fr : "les gouttes"},
{en : "government", fr : "le gouvernement"},
{en : "insects", fr : "les insectes"},
{en : "napkin", fr : "la serviette"},
{en : "hail", fr : "la grêle"},
{en : "attic", fr : "le grenier"},
{en : "flu", fr : "la grippe"},
{en : "beans", fr : "les haricots"},
{en : "time", fr : "l'heure"},
{en : "yesterday", fr : "hier"},
{en : "story", fr : "l'histoire"},
{en : "shorts", fr : "le short"},
{en : "winter", fr : "l'hiver"},
{en : "hockey", fr : "le hockey"},
{en : "cup", fr : "la tasse"},
{en : "tomato", fr : "la tomate"},
{en : "war", fr : "la guerre"},
{en : "counter", fr : "le guichet"},
{en : "guitar", fr : "la guitare"},
{en : "son-in-law", fr : "le gendre"},
{en : "hip", fr : "la hanche"},
{en : "ham", fr : "le jambon"},
{en : "skyscraper", fr : "le gratte-ciel"},
{en : "lobster", fr : "le homard"},
{en : "hospital", fr : "l'hôpital"},
{en : "clock", fr : "l'horloge"},
{en : "appetizers", fr : "les hors-d'oeuvres"},
{en : "hotel", fr : "l'hôtel"},
{en : "oil", fr : "l'huile"},
{en : "island", fr : "l'île"},
{en : "raincoat", fr : "l'imperméable"},
{en : "taxes", fr : "les impôts"},
{en : "sauce", fr : "la sauce"},
{en : "jump", fr : "le saut"},
{en : "knee", fr : "le genou"},
{en : "people", fr : "les gens"},
{en : "vest", fr : "le gilet"},
{en : "ice cream", fr : "la glace"},
{en : "ice cubes", fr : "les glaçons"},
{en : "throat", fr : "la gorge"},
{en : "taste", fr : "le goût"},
{en : "snack", fr : "le goûter"},
{en : "second", fr : "la seconde"},
{en : "wind", fr : "le vent"},
{en : "windowpane", fr : "la vitre"},
{en : "face", fr : "le visage"},
{en : "roof", fr : "le toit"},
{en : "sheet", fr : "le drap"},
{en : "law", fr : "le droit"},
{en : "doctor", fr : "le docteur"},
{en : "aunt", fr : "la tante"},
{en : "pain", fr : "la douleur"},
{en : "church", fr : "l'église"},
{en : "pupil", fr : "l'élève"},
{en : "tomorrow", fr : "demain"},
{en : "boring", fr : "ennuyeux"},
{en : "brilliant/sparking", fr : "étincelant"},
{en : "cold", fr : "froid"},
{en : "courageous", fr : "courageux"},
{en : "dark", fr : "foncé"},
{en : "delicious", fr : "délicieux"},
{en : "different", fr : "différent"},
{en : "disloyal", fr : "déloyal"},
{en : "dull", fr : "terne (appearance)"},
{en : "dumb", fr : "idiot"},
{en : "easy", fr : "facile"},
{en : "empty", fr : "vide"},
{en : "energetic", fr : "énergique"},
{en : "evil", fr : "mal"},
{en : "few", fr : "peu"},
{en : "fragrant", fr : "parfumé"},
{en : "fun", fr : "amusant"},
{en : "happy", fr : "content/heureux"},
{en : "hard (not easy)", fr : "difficile"},
{en : "hard (not soft)", fr : "dur"},
{en : "heavy", fr : "lourd"},
{en : "hot", fr : "chaud"},
{en : "humble", fr : "humble"},
{en : "immature", fr : "immature"},
{en : "important", fr : "important"},
{en : "jealous", fr : "jaloux"},
{en : "large", fr : "grand"},
{en : "light", fr : "léger"},
{en : "loving", fr : "aimant"},
{en : "mad", fr : "fâché"},
{en : "near", fr : "près (de)"},
{en : "new", fr : "nouveau"},
{en : "nice", fr : "gentil"},
{en : "round", fr : "rond"},
{en : "same", fr : "même"},
{en : "scared", fr : "effrayé"},
{en : "scary", fr : "effrayant"},
{en : "shiny", fr : "brillant"},
{en : "short", fr : "court"},
{en : "shut", fr : "fermé"},
{en : "shy", fr : "timide"},
{en : "sickly", fr : "chétif ou maladif"},
{en : "silly", fr : "loufoque"},
{en : "slow", fr : "lent"},
{en : "small", fr : "petit"},
{en : "smart", fr : "intelligent"},
{en : "smelly", fr : "malororant/fétide"},
{en : "spicy", fr : "épicé"},
{en : "square", fr : "carré"},
{en : "strong", fr : "fort"},
{en : "suspicious", fr : "suspicieux"},
{en : "tall", fr : "grand"},
{en : "thick", fr : "épais"},
{en : "thin", fr : "mince"},
{en : "unfriendly", fr : "ennemi"},
{en : "useless", fr : "inutile"},
{en : "friendly", fr : "amical"},
{en : "other", fr : "autre"},
{en : "beautiful/handsome", fr : "beau"},
{en : "a lot", fr : "beaucoup"},
{en : "good", fr : "bon"},
{en : "hard working", fr : "bosseur"},
{en : "loud", fr : "bruyant"},
{en : "quiet", fr : "calme"},
{en : "lucky", fr : "chanceux"},
{en : "light", fr : "claire"},
{en : "disgusting", fr : "dégoutant"},
{en : "last", fr : "dernier"},
{en : "trustworthy", fr : "digne de confiance"},
{en : "mild", fr : "doux (pas épicé)"},
{en : "soft", fr : "doux (pas dur)"},
{en : "hateful", fr : "ennemi"},
{en : "angry", fr : "fâché"},
{en : "weak", fr : "faible"},
{en : "tired", fr : "fatigué"},
{en : "loyal", fr : "fidèle"},
{en : "prideful", fr : "fier"},
{en : "cool", fr : "frais"},
{en : "confused/embarrassed", fr : "gêné"},
{en : "young", fr : "jeune"},
{en : "righteous", fr : "juste"},
{en : "loose", fr : "lâche"},
{en : "ugly", fr : "laid"},
{en : "unfortunate", fr : "malheureux"},
{en : "dishonest", fr : "malhonnête"},
{en : "bad", fr : "mauvais"},
{en : "mean", fr : "méchant"},
{en : "better/best", fr : "meilleur"},
{en : "mature", fr : "mûr"},
{en : "open", fr : "ouvert"},
{en : "lazy", fr : "paresseux"},
{en : "full", fr : "plein"},
{en : "worse/worst", fr : "plus mal / pire"},
{en : "first", fr : "premier"},
{en : "next", fr : "prochain"},
{en : "clean", fr : "propre"},
{en : "fast", fr : "rapide"},
{en : "reverent (high form of respect)", fr : "respectueux"},
{en : "healthy", fr : "sain"},
{en : "dirty", fr : "sale"},
{en : "outgoing", fr : "sociable"},
{en : "tight", fr : "tendu"},
{en : "sad", fr : "triste"},
{en : "useful", fr : "utile"},
{en : "old", fr : "vieux"},
{en : "vibrant/living", fr : "vivant"}
];
